[package]
name = "rust-dataflow-example-sink"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = "0.3.5"
eyre = "0.6.8"
